# Generated by Django 3.1.1 on 2021-04-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('attemptId', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(default='', max_length=500, null=True)),
                ('qAttempter', models.CharField(default='', max_length=500, null=True)),
                ('totalQue', models.IntegerField(default=0)),
                ('attemptedQue', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('attemptedtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('option1', models.CharField(default='', max_length=500)),
                ('option2', models.CharField(default='', max_length=500)),
                ('option3', models.CharField(default='', max_length=500)),
                ('option4', models.CharField(default='', max_length=500)),
                ('answer', models.CharField(default='', max_length=500)),
                ('catogaries', models.CharField(default='', max_length=500)),
                ('hint', models.CharField(default='', max_length=500)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.quiz')),
                ('testId', models.CharField(max_length=500)),
                ('Quiz_cover', models.ImageField(blank=True, null=True, upload_to='QuizCover')),
            ],
            bases=('blog.quiz',),
        ),
    ]
