# Generated by Django 3.1.1 on 2021-04-08 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210406_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='accuracy',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 57, 13, 91035)),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='correct',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='catogaries',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
