# Generated by Django 3.1.1 on 2021-04-08 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210408_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 57, 57, 758726)),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
