# Generated by Django 3.0.5 on 2020-04-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_quiz_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz_page',
        ),
    ]
