# Generated by Django 3.1.1 on 2021-02-02 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_quiz_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('attemptId', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(default='', max_length=500, null=True)),
                ('qAttempter', models.CharField(default='', max_length=500, null=True)),
                ('totalQue', models.IntegerField(default=0)),
                ('attemptedQue', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('attemptedtime', models.DateTimeField(default=datetime.datetime(2021, 2, 2, 12, 48, 37, 885883))),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='catogaries',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
