# Generated by Django 3.1.1 on 2021-02-02 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210202_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('quiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.quiz')),
                ('testId', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('blog.quiz',),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 20, 2, 48, 620958)),
        ),
    ]
