# Generated by Django 3.1.1 on 2021-02-02 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210202_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 20, 13, 38, 991264)),
        ),
        migrations.AlterField(
            model_name='test',
            name='testId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
