# Generated by Django 3.1.1 on 2021-02-02 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210202_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 20, 36, 7, 538736)),
        ),
        migrations.AlterField(
            model_name='test',
            name='quiz_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.quiz'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testId',
            field=models.CharField(max_length=500),
        ),
    ]
