# Generated by Django 3.1.1 on 2021-02-02 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210202_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='accuracy',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 35, 39, 863500)),
        ),
    ]
