# Generated by Django 3.1.1 on 2021-02-02 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210202_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 59, 47, 584590)),
        ),
    ]
