# Generated by Django 3.1.1 on 2021-02-03 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210203_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 13, 16, 11, 632811)),
        ),
        migrations.AlterField(
            model_name='test',
            name='Quiz_cover',
            field=models.ImageField(blank=True, null=True, upload_to='QuizCover/'),
        ),
    ]
