# Generated by Django 3.1.1 on 2021-02-03 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210203_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 13, 32, 39, 752470)),
        ),
        migrations.AlterField(
            model_name='test',
            name='Quiz_cover',
            field=models.FileField(blank=True, null=True, upload_to='QuizCover/'),
        ),
    ]
