# Generated by Django 3.1.1 on 2021-04-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210406_1522'),
        ('blog', '0005_auto_20210408_1558'),
    ]

    operations = [
    ]
