# Generated by Django 3.1.1 on 2021-04-08 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_merge_20210408_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='attemptedtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 21, 1, 19, 71961)),
        ),
    ]
