# Generated by Django 3.0.5 on 2020-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_quiz_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='catogaries',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
