# Generated by Django 3.0.5 on 2020-04-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200427_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='catogaries',
        ),
    ]
